import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/font-size.toml", "~/.local/share/omakub/defaults/alacritty.toml" ]

[window.dimensions]
columns = 130
lines = 35

#[keyboard]
#bindings = [
#    { key='C', mods='Control', action='Copy' },
#    { key='V', mods='Control', action='Paste' }
#]
