[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    # "~/.config/alacritty/theme.toml", 
    "~/.config/alacritty/font.toml", 
    "~/.config/alacritty/font-size.toml"
]

[window.dimensions]
columns = 112
lines = 35

#[keyboard]
#bindings = [
#    { key='C', mods='Control', action='Copy' },
#    { key='V', mods='Control', action='Paste' }
#]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "fish"
args = ["-l", "-c", "zellij"]

[window]
padding.x = 3
padding.y = 3
# decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[terminal]
